stages:
  - build
  - deploy

build:
  image: node:latest
  stage: build
  script:
    - npm install -g @angular/cli@latest
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour


deploy:
  image: python:latest
  stage: deploy
  only:
    - dev
  script:
    - pip3 install awscli
    - aws configure set AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
    - aws configure set AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY
    - aws configure set AWS_DEFAULT_REGION $AWS_DEFAULT_REGION

    - aws s3 rm s3://virtual-institute --recursive
    - aws s3 sync ./dist s3://virtual-institute --acl public-read